name: Auto-Update Leaderboard

on:
  schedule:
    # Runs every 15 minutes.
    - cron: '*/15 * * * *'
  workflow_dispatch: # Allows you to run it manually from the GitHub UI

jobs:
  update-leaderboard:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Leaderboard-Backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Create Service Account Key
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > leaderboard-f251e-firebase-adminsdk-fbsvc-f6e4b962c1.json

      - name: Generate JSON
        run: node Leaderboard.js

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/Leaderboard-Backend/leaderboard-f251e-firebase-adminsdk-fbsvc-f6e4b962c1.json
        run: npx firebase-tools deploy --only hosting --project leaderboard-f251e
